In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler

In [65]:
x=pd.read_csv("1.02.+Multiple+linear+regression.csv")

In [66]:
y=x[["SAT"]]
x=x.drop(["SAT"],axis=1)

In [67]:
scaler=StandardScaler()

In [68]:
scaler.fit(x)

StandardScaler()

In [69]:
x_scaled=scaler.transform(x)

In [70]:
x_scaled

array([[-3.44538388, -1.24637147],
       [-3.00093201,  1.10632974],
       [-2.92685669,  1.10632974],
       [-2.18610357,  1.10632974],
       [-1.85276466, -0.07002087],
       [-1.55646341, -1.24637147],
       [-1.22312451, -0.07002087],
       [-1.22312451, -1.24637147],
       [-1.18608685, -0.07002087],
       [-1.18608685,  1.10632974],
       [-1.14904919,  1.10632974],
       [-0.96386091, -0.07002087],
       [-0.92682326, -1.24637147],
       [-0.92682326,  1.10632974],
       [-0.77867263, -0.07002087],
       [-0.59348435, -0.07002087],
       [-0.59348435,  1.10632974],
       [-0.59348435, -0.07002087],
       [-0.59348435,  1.10632974],
       [-0.51940904,  1.10632974],
       [-0.51940904,  1.10632974],
       [-0.51940904,  1.10632974],
       [-0.48237138,  1.10632974],
       [-0.44533372, -1.24637147],
       [-0.33422076, -1.24637147],
       [-0.18607013, -1.24637147],
       [-0.18607013, -1.24637147],
       [-0.18607013,  1.10632974],
       [-0.18607013,

In [71]:
lm=LinearRegression()

In [72]:
lm.fit(x_scaled,y)

LinearRegression()

In [73]:
lm.coef_

array([[66.19673541, -0.23624296]])

In [74]:
lm.intercept_

array([1845.27380952])

In [75]:
summary=pd.DataFrame([["Intercept"],["GPA"],["Rand 1,2,3"]],columns=["Features"])
summary["Weights"]=lm.intercept_[0],lm.coef_[0][0],lm.coef_[0][1]

In [64]:
summary

Features      Weights
0   Intercept  1845.273810
1         GPA    66.196735
2  Rand 1,2,3    -0.236243