In [1]:
import pandas as pd
import numpy as np
import scipy.stats as  stats
import matplotlib.pyplot as plt
import seaborn as sns 

# 1.You flip a fair coin 10 times. What is the probability of getting 8 or more heads? 

In [6]:
stats.binom.pmf(n=10,p=0.5,k=np.arange(8,11))

array([0.04394531, 0.00976563, 0.00097656])

In [43]:
#  when 8 aor more
y=stats.binom.pmf(n=10,p=0.5,k=np.arange(8,11))
y

array([0.04394531, 0.00976563, 0.00097656])

# 2. The probability that you will win a certain game is 0.3. You play the game 20 times. What is the mean of this binomial distribution?


In [8]:
#  mean   formula for  binormal distributions is np
# n= number of counts
# p= is the probability
mean=(20*.3)
mean

6.0

# 3. An automatic camera records the number of cars running a red light at an intersection (that is, the cars were going through when the red light was against the car). Analysis of the data shows that on average 15% of light changes record a car running a red light. Assume that the data has a binomial distribution. What is theprobability that in 20 light changes there will be exactly three (3) cars running a red light?

In [10]:
stats.binom.pmf(n=20,p=0.15,k=3)

0.24282889614926725

# 4. There are 15 sets of traffic lights on the journey.The probability that a driver must stop at any one traffic light coming to alliance University is 0.3  

a) What is the probability that a student must stop at exactly 2 of the 15 sets oftraffic lights? 

b) What is the probability that a student will be stopped at 1 or more of the 15sets of traffic lights? 

In [13]:
a=stats.binom.pmf(n=15,p=0.3,k=2)
a

0.0915601148346156

In [21]:
#  when  more than 1 
b=stats.binom.pmf(n=15,p=0.3,k=0)
1-b

0.995252438490057

# 5. What is the area under the curve of a probability distribution? Explain.

The area under the cure is 1 means that the probability that a score chosen at  random will occur under the curve is 1

# 6. My Bank has a large Credit Card portfolio. Based on empirical data, they have found that 60% of the customers pay their bill on time. If a sample of 10 accounts is selected from the current database, construct the Probability Distribution of accounts paying on time.
Hint: Make use of Function used in Excel or R

In [44]:
stats.binom.pmf(n=10,p=.6,k=np.arange(1,11))

array([0.00157286, 0.01061683, 0.04246733, 0.11147674, 0.20065812,
       0.25082266, 0.21499085, 0.12093235, 0.04031078, 0.00604662])

# 7. If the likelihood of a tagged order form is 0.1, What is the probability that there are three tagged order forms in the sample of four?
Hint: Use Binomial distribution equation

In [45]:
stats.binom.pmf(n=4,p=0.1,k=3)

0.003600000000000003

# 8. Determine the following:

a) For n = 4 and p = 0.12, what is P(X = 0)?

b) For n = 6 and p = 0.83, what is P(X = 5)?

In [51]:
a=stats.binom.pmf(n=4,p=0.12,k=0)
b=stats.binom.pmf(n=6,p=0.12,k=5)
print("a  :",a)
print("b  :",b)

a  : 0.59969536
b  : 0.00013138329599999985


# 9.Determine the mean and standard deviation of the variable X in each of the following binomial distributions:

a) n = 4 and p = 0.10

b) n = 5 and p = 0.80

In [77]:
#  mean formula =np
#  standard deviation fromula sqrt(np(1-p))
p=1-0.10
mean=(4*0.10)
Sd=mean*p
SD=np.sqrt(Sd)
print("mean: " ,mean)
print("Standard deviation: " ,SD)

mean:  0.4
Standard deviation:  0.6000000000000001


In [78]:
p=1-0.80
mean=(5*0.80)
Sd=mean*p
SD=np.sqrt(Sd)
print("mean: " ,mean)
print("Standard deviation: " ,SD)

mean:  4.0
Standard deviation:  0.8944271909999157


# 10. Assume a poisson distribution with lambda = 5.0. What is the probability that
a) X <= 1?

b) X > 1?

In [112]:
b=stats.poisson.pmf(k=np.arange(0,2),mu=5)
b[0]+b[1]

0.040427681994512805

In [100]:
b=stats.poisson.pmf(k=np.arange(0,2),mu=5)
1-(a[0]+a[1])

0.9595723180054871

# 11. The number of work related injuries per month in a manufacturing plant is known to follow a Poisson distribution, with a mean of 2.5 work-related injuries a month.

a) What is the probability that in a given month, no work-related injuries occur?

b) That at least one work- related injury occurs?

Hint: Use Poisson distribution equation, find X = 0, Given lambda = 2.5

In [113]:
stats.poisson.pmf(k=0,mu=2.5)

0.0820849986238988

In [115]:
x=stats.poisson.pmf(k=0,mu=2.5)
1-x

0.9179150013761012

# 12. A 5-litre bucket of water is taken from a swamp. The water contains 75 mosquito larvae. A 200mL flask of water is taken form the bucket for further analysis. What is

a) the expected number of larvae in the flask?

b) the probability that the flask contains at least one mosquito lava?

In [120]:
# IN 5l 75 larvaes meaning= 5000/75= 200l 3 larves  

In [119]:
x=stats.poisson.pmf(k=0,mu=3)
1-x

0.950212931632136

# 13. Why the need of Standardization? Why do we us Z instead of “the Number of Standard Deviations”?

Normally Distributed random variable take on many different units of measure: rupees, cms, inches, Kg, minutes. By standardizing, you remove the units as such we do not require separate Normal Distribution table for each variable and one Standardized Distribution Table can be used for any random variable.

# 14. A radar unit is used to measure speeds of cars on a Mumbai – Pune Highway. The speeds are normally distributed with a mean of 70 km/hr and a standard deviation of 10 km/hr.

a)What is the probability that a car picked at random is travelling at more than 100 km/hr?

b)What is the probability that the car speed is between 80 Km / hr and 100 Km / hr

Hint: You can make use of Excel

In [123]:
x=stats.norm.cdf(100,loc=70,scale=10)
1-x

0.0013498980316301035

In [124]:
z = (100 - 70)/10
1 - (stats.norm.cdf(z))

0.0013498980316301035

In [126]:
stats.norm.cdf(100,loc=70,scale=10)-stats.norm.cdf(80,loc=70,scale=10)

0.15730535589982697

In [127]:
z1 = (80-70)/10
stats.norm.cdf(z) - stats.norm.cdf(z1)

0.15730535589982697

# 15. The percentage of orders filled correctly at Wendy's was approximately 86.8%. Suppose that you go to drive-through window at Wendy's and place an order. Two friends of yours independently place orders at the drive-through window at the same Wendy's.

What are the probabilities that

a) all three filled correctly?

b) none of the three filled correctly?

c) atleast two of the three orders will be filled correctly?

d) what is the mean and standard deviation of the orders filled correctly?

In [142]:
p=.868
n=3
prob=(1-p)

In [134]:
a=stats.binom.pmf(n=n,p=p,k=3)
print("all three filled correctly? :",a)

all three filled correctly? : 0.653972032


In [135]:
b=stats.binom.pmf(n=n,p=p,k=0)
print("none of the three filled correctly? :" , b)b

0.002299968

In [147]:
c=stats.binom.pmf(n=n,p=p,k=1)
print("atleast two of the three orders will be filled correctly?: ",1-c)

atleast two of the three orders will be filled correctly?:  0.954627904


In [143]:
mean=n*p
SD=np.sqrt(mean*prob)

In [145]:
print("d) what is the mean and standard deviation of the orders filled correctly?: " ,mean,SD)

d) what is the mean and standard deviation of the orders filled correctly?:  2.604 0.5862832080146932
